In [1]:
import pandas as pd

In [2]:
df_2010 = pd.read_csv("./datasets/ecommerce2010.csv")
df_2011 = pd.read_csv("./datasets/ecommerce2011.csv")

In [3]:
df_2010.head(7) # top 7 rows (1)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12-01-2010 08:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12-01-2010 08:26,4.25,17850.0,United Kingdom

In [4]:
df_2010.tail(7) # last 7 rows (2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
17408,538529,85123A,WHITE HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290.0,United Kingdom
17409,538529,22804,CANDLEHOLDER PINK HANGING HEART,6,12/13/2010 10:24,2.95,14290.0,United Kingdom
17410,538529,21733,RED HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290.0,United Kingdom
17411,538529,21741,COSY SLIPPER SHOES LARGE GREEN,6,12/13/2010 10:24,2.95,14290.0,United Kingdom
17412,538529,21485,RETROSPOT HEART HOT WATER BOTTLE,6,12/13/2010 10:24,4.95,14290.0,United Kingdom
17413,538529,22112,CHOCOLATE HOT WATER BOTTLE,12,12/13/2010 10:24,4.95,14290.0,United Kingdom
17414,538529,22835,HOT WATER BOTTLE I AM SO POORLY,4,12/13/2010 10:24,4.65,14290.0,United Kingdom

In [5]:
df_2010.dtypes # data type of all columns (3)

InvoiceNo        int64
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [6]:
df_2010.isnull().sum() # checking if there is null value or not (4)

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [7]:
print("dimensions of dataframe :",df_2010.shape) #no of columns and rows (5)
print("Number of rows: ",df_2010.shape[0])
print("Number of columns: ",df_2010.shape[1])

dimensions of dataframe : (17415, 8)
Number of rows:  17415
Number of columns:  8

In [8]:
df_2010.groupby("InvoiceNo")["Quantity"].sum() # how many items per cart i.e invoice (6)

InvoiceNo
536365     40
536366     12
536367     83
536368     15
536369      3
         ...
538525    300
538526    864
538527    336
538528     56
538529     98
Name: Quantity, Length: 899, dtype: int64

In [9]:
for key,value in df_2010.groupby("InvoiceNo").InvoiceDate: #proof
    print(key)
    print(value)

536365
0    12-01-2010 08:26
1    12-01-2010 08:26
2    12-01-2010 08:26
3    12-01-2010 08:26
4    12-01-2010 08:26
5    12-01-2010 08:26
6    12-01-2010 08:26
Name: InvoiceDate, dtype: object
536366
7    12-01-2010 08:28
8    12-01-2010 08:28
Name: InvoiceDate, dtype: object
536367
9     12-01-2010 08:34
10    12-01-2010 08:34
11    12-01-2010 08:34
12    12-01-2010 08:34
13    12-01-2010 08:34
14    12-01-2010 08:34
15    12-01-2010 08:34
16    12-01-2010 08:34
17    12-01-2010 08:34
18    12-01-2010 08:34
19    12-01-2010 08:34
20    12-01-2010 08:34
Name: InvoiceDate, dtype: object
536368
21    12-01-2010 08:34
22    12-01-2010 08:34
23    12-01-2010 08:34
24    12-01-2010 08:34
Name: InvoiceDate, dtype: object
536369
25    12-01-2010 08:35
Name: InvoiceDate, dtype: object
536370
26    12-01-2010 08:45
27    12-01-2010 08:45
28    12-01-2010 08:45
29    12-01-2010 08:45
30    12-01-2010 08:45
31    12-01-2010 08:45
32    12-01-2010 08:45
33    12-01-2010 08:45
34    12-01-2010 08:45
35    12-01-2010 08:45
36    12-01-2010 08:45
37    12-01-2010 08:45
38    12-01-2010 08:45
39    12-01-2010 08:45
40    12-01-2010 08:45
41    12-01-2010 08:45
42    12-01-2010 08:45
43    12-01-2010 08:45
44    12-01-2010 08:45
45    12-01-2010 08:45
Name: InvoiceDate, dtype: object
536371
46    12-01-2010 09:00
Name: InvoiceDate, dtype: object
536372
47    12-01-2010 09:01
48    12-01-2010 09:01
Name: InvoiceDate, dtype: object
536373
49    12-01-2010 09:02
50    12-01-2010 09:02
51    12-01-2010 09:02
52    12-01-2010 09:02
53    12-01-2010 09:02
54    12-01-2010 09:02
55    12-01-2010 09:02
56    12-01-2010 09:02
57    12-01-2010 09:02
58    12-01-2010 09:02
59    12-01-2010 09:02
60    12-01-2010 09:02
61    12-01-2010 09:02
62    12-01-2010 09:02
63    12-01-2010 09:02
64    12-01-2010 09:02
Name: InvoiceDate, dtype: object
536374
65    12-01-2010 09:09
Name: InvoiceDate, dtype: object
536375
66    12-01-2010 09:32
67    12-01-2010 09:32
68    12-01-2010 09:32
69    12-01-2010 09:32
70    12-01-2010 09:32
71    12-01-2010 09:32
72    12-01-2010 09:32
73    12-01-2010 09:32
74    12-01-2010 09:32
75    12-01-2010 09:32
76    12-01-2010 09:32
77    12-01-2010 09:32
78    12-01-2010 09:32
79    12-01-2010 09:32
80    12-01-2010 09:32
81    12-01-2010 09:32
Name: InvoiceDate, dtype: object
536376
82    12-01-2010 09:32
83    12-01-2010 09:32
Name: InvoiceDate, dtype: object
536377
84    12-01-2010 09:34
85    12-01-2010 09:34
Name: InvoiceDate, dtype: object
536378
86     12-01-2010 09:37
87     12-01-2010 09:37
88     12-01-2010 09:37
89     12-01-2010 09:37
90     12-01-2010 09:37
91     12-01-2010 09:37
92     12-01-2010 09:37
93     12-01-2010 09:37
94     12-01-2010 09:37
95     12-01-2010 09:37
96     12-01-2010 09:37
97     12-01-2010 09:37
98     12-01-2010 09:37
99     12-01-2010 09:37
100    12-01-2010 09:37
101    12-01-2010 09:37
102    12-01-2010 09:37
103    12-01-2010 09:37
104    12-01-2010 09:37
Name: InvoiceDate, dtype: object
536380
105    12-01-2010 09:41
Name: InvoiceDate, dtype: object
536381
106    12-01-2010 09:41
107    12-01-2010 09:41
108    12-01-2010 09:41
109    12-01-2010 09:41
110    12-01-2010 09:41
111    12-01-2010 09:41
112    12-01-2010 09:41
113    12-01-2010 09:41
114    12-01-2010 09:41
115    12-01-2010 09:41
116    12-01-2010 09:41
117    12-01-2010 09:41
118    12-01-2010 09:41
119    12-01-2010 09:41
120    12-01-2010 09:41
121    12-01-2010 09:41
122    12-01-2010 09:41
123    12-01-2010 09:41
124    12-01-2010 09:41
125    12-01-2010 09:41
126    12-01-2010 09:41
127    12-01-2010 09:41
128    12-01-2010 09:41
129    12-01-2010 09:41
130    12-01-2010 09:41
131    12-01-2010 09:41
132    12-01-2010 09:41
133    12-01-2010 09:41
134    12-01-2010 09:41
135    12-01-2010 09:41
136    12-01-2010 09:41
137    12-01-2010 09:41
138    12-01-2010 09:41
139    12-01-2010 09:41
140    12-01-2010 09:41
Name: InvoiceDate, dtype: object
536382
141    12-01-2010 09:45
142    12-01-2010 09:45
143    12-01-2010 09:45
144    12-01-2010 09:45
145    12-01-2010 09:45
146    12-01-2010 09:45
147    12-01-2010 09:45
148    12-01-2010 09:45
149    12-01-2010 09:45
150    12-01-2010 09:45
151    12-01-2010 09:45
152    12-01-2010 09:45
Name: InvoiceDate, dtype: object
536384
153    12-01-2010 09:53
154    12-01-2010 09:53
155    12-01-2010 09:53
156    12-01-2010 09:53
157    12-01-2010 09:53
158    12-01-2010 09:53
159    12-01-2010 09:53
160    12-01-2010 09:53
161    12-01-2010 09:53
162    12-01-2010 09:53
163    12-01-2010 09:53
164    12-01-2010 09:53
165    12-01-2010 09:53
Name: InvoiceDate, dtype: object
536385
166    12-01-2010 09:56
167    12-01-2010 09:56
168    12-01-2010 09:56
169    12-01-2010 09:56
170    12-01-2010 09:56
171    12-01-2010 09:56
172    12-01-2010 09:56
Name: InvoiceDate, dtype: object
536386
173    12-01-2010 09:57
174    12-01-2010 09:57
175    12-01-2010 09:57
Name: InvoiceDate, dtype: object
536387
176    12-01-2010 09:58
177    12-01-2010 09:58
178    12-01-2010 09:58
179    12-01-2010 09:58
180    12-01-2010 09:58
Name: InvoiceDate, dtype: object
536388
181    12-01-2010 09:59
182    12-01-2010 09:59
183    12-01-2010 09:59
184    12-01-2010 09:59
185    12-01-2010 09:59
186    12-01-2010 09:59
187    12-01-2010 09:59
188    12-01-2010 09:59
189    12-01-2010 09:59
190    12-01-2010 09:59
191    12-01-2010 09:59
192    12-01-2010 09:59
193    12-01-2010 09:59
194    12-01-2010 09:59
Name: InvoiceDate, dtype: object
536389
195    12-01-2010 10:03
196    12-01-2010 10:03
197    12-01-2010 10:03
198    12-01-2010 10:03
199    12-01-2010 10:03
200    12-01-2010 10:03
201    12-01-2010 10:03
202    12-01-2010 10:03
203    12-01-2010 10:03
204    12-01-2010 10:03
205    12-01-2010 10:03
206    12-01-2010 10:03
207    12-01-2010 10:03
208    12-01-2010 10:03
Name: InvoiceDate, dtype: object
536390
209    12-01-2010 10:19
210    12-01-2010 10:19
211    12-01-2010 10:19
212    12-01-2010 10:19
213    12-01-2010 10:19
214    12-01-2010 10:19
215    12-01-2010 10:19
216    12-01-2010 10:19
217    12-01-2010 10:19
218    12-01-2010 10:19
219    12-01-2010 10:19
220    12-01-2010 10:19
221    12-01-2010 10:19
222    12-01-2010 10:19
223    12-01-2010 10:19
224    12-01-2010 10:19
225    12-01-2010 10:19
226    12-01-2010 10:19
227    12-01-2010 10:19
228    12-01-2010 10:19
229    12-01-2010 10:19
230    12-01-2010 10:19
231    12-01-2010 10:19
232    12-01-2010 10:19
Name: InvoiceDate, dtype: object
536392
233    12-01-2010 10:29
234    12-01-2010 10:29
235    12-01-2010 10:29
236    12-01-2010 10:29
237    12-01-2010 10:29
238    12-01-2010 10:29
239    12-01-2010 10:29
240    12-01-2010 10:29
241    12-01-2010 10:29
242    12-01-2010 10:29
Name: InvoiceDate, dtype: object
536393
243    12-01-2010 10:37
Name: InvoiceDate, dtype: object
536394
244    12-01-2010 10:39
245    12-01-2010 10:39
246    12-01-2010 10:39
247    12-01-2010 10:39
248    12-01-2010 10:39
249    12-01-2010 10:39
250    12-01-2010 10:39
251    12-01-2010 10:39
252    12-01-2010 10:39
253    12-01-2010 10:39
254    12-01-2010 10:39
Name: InvoiceDate, dtype: object
536395
255    12-01-2010 10:47
256    12-01-2010 10:47
257    12-01-2010 10:47
258    12-01-2010 10:47
259    12-01-2010 10:47
260    12-01-2010 10:47
261    12-01-2010 10:47
262    12-01-2010 10:47
263    12-01-2010 10:47
264    12-01-2010 10:47
265    12-01-2010 10:47
266    12-01-2010 10:47
267    12-01-2010 10:47
268    12-01-2010 10:47
Name: InvoiceDate, dtype: object
536396
269    12-01-2010 10:51
270    12-01-2010 10:51
271    12-01-2010 10:51
272    12-01-2010 10:51
273    12-01-2010 10:51
274    12-01-2010 10:51
275    12-01-2010 10:51
276    12-01-2010 10:51
277    12-01-2010 10:51
278    12-01-2010 10:51
279    12-01-2010 10:51
280    12-01-2010 10:51
281    12-01-2010 10:51
282    12-01-2010 10:51
283    12-01-2010 10:51
284    12-01-2010 10:51
285    12-01-2010 10:51
286    12-01-2010 10:51
Name: InvoiceDate, dtype: object
536397
287    12-01-2010 10:51
288    12-01-2010 10:51
Name: InvoiceDate, dtype: object
536398
289    12-01-2010 10:52
290    12-01-2010 10:52
291    12-01-2010 10:52
292    12-01-2010 10:52
293    12-01-2010 10:52
294    12-01-2010 10:52
295    12-01-2010 10:52
296    12-01-2010 10:52
297    12-01-2010 10:52
298    12-01-2010 10:52
299    12-01-2010 10:52
300    12-01-2010 10:52
301    12-01-2010 10:52
302    12-01-2010 10:52
303    12-01-2010 10:52
304    12-01-2010 10:52
305    12-01-2010 10:52
Name: InvoiceDate, dtype: object
536399
306    12-01-2010 10:52
307    12-01-2010 10:52
Name: InvoiceDate, dtype: object
536400
308    12-01-2010 10:53
Name: InvoiceDate, dtype: object
536401
309    12-01-2010 11:21
310    12-01-2010 11:21
311    12-01-2010 11:21
312    12-01-2010 11:21
313    12-01-2010 11:21
             ...
368    12-01-2010 11:21
369    12-01-2010 11:21
370    12-01-2010 11:21
371    12-01-2010 11:21
372    12-01-2010 11:21
Name: InvoiceDate, Length: 64, dtype: object
536402
373    12-01-2010 11:22
374    12-01-2010 11:22
375    12-01-2010 11:22
Name: InvoiceDate, dtype: object
536403
376    12-01-2010 11:27
377    12-01-2010 11:27
Name: InvoiceDate, dtype: object
536404
378    12-01-2010 11:29
379    12-01-2010 11:29
380    12-01-2010 11:29
381    12-01-2010 11:29
382    12-01-2010 11:29
383    12-01-2010 11:29
384    12-01-2010 11:29
385    12-01-2010 11:29
386    12-01-2010 11:29
387    12-01-2010 11:29
388    12-01-2010 11:29
389    12-01-2010 11:29
390    12-01-2010 11:29
391    12-01-2010 11:29
392    12-01-2010 11:29
393    12-01-2010 11:29
394    12-01-2010 11:29
395    12-01-2010 11:29
396    12-01-2010 11:29
397    12-01-2010 11:29
398    12-01-2010 11:29
399    12-01-2010 11:29
400    12-01-2010 11:29
401    12-01-2010 11:29
402    12-01-2010 11:29
403    12-01-2010 11:29
404    12-01-2010 11:29
405    12-01-2010 11:29
Name: InvoiceDate, dtype: object
536405
406    12-01-2010 11:32
Name: InvoiceDate, dtype: object
536406
407    12-01-2010 11:33
408    12-01-2010 11:33
409    12-01-2010 11:33
410    12-01-2010 11:33
411    12-01-2010 11:33
412    12-01-2010 11:33
413    12-01-2010 11:33
414    12-01-2010 11:33
415    12-01-2010 11:33
416    12-01-2010 11:33
417    12-01-2010 11:33
418    12-01-2010 11:33
419    12-01-2010 11:33
420    12-01-2010 11:33
421    12-01-2010 11:33
422    12-01-2010 11:33
423    12-01-2010 11:33
Name: InvoiceDate, dtype: object
536407
424    12-01-2010 11:34
425    12-01-2010 11:34
Name: InvoiceDate, dtype: object
536408
426    12-01-2010 11:41
427    12-01-2010 11:41
428    12-01-2010 11:41
429    12-01-2010 11:41
430    12-01-2010 11:41
431    12-01-2010 11:41
432    12-01-2010 11:41
433    12-01-2010 11:41
434    12-01-2010 11:41
435    12-01-2010 11:41
436    12-01-2010 11:41
437    12-01-2010 11:41
438    12-01-2010 11:41
439    12-01-2010 11:41
440    12-01-2010 11:41
441    12-01-2010 11:41
442    12-01-2010 11:41
443    12-01-2010 11:41
444    12-01-2010 11:41
445    12-01-2010 11:41
446    12-01-2010 11:41
447    12-01-2010 11:41
448    12-01-2010 11:41
449    12-01-2010 11:41
450    12-01-2010 11:41
451    12-01-2010 11:41
452    12-01-2010 11:41
453    12-01-2010 11:41
454    12-01-2010 11:41
455    12-01-2010 11:41
456    12-01-2010 11:41
457    12-01-2010 11:41
458    12-01-2010 11:41
459    12-01-2010 11:41
460    12-01-2010 11:41
461    12-01-2010 11:41
462    12-01-2010 11:41
463    12-01-2010 11:41
464    12-01-2010 11:41
465    12-01-2010 11:41
466    12-01-2010 11:41
467    12-01-2010 11:41
468    12-01-2010 11:41
469    12-01-2010 11:41
470    12-01-2010 11:41
471    12-01-2010 11:41
472    12-01-2010 11:41
473    12-01-2010 11:41
Name: InvoiceDate, dtype: object
536409
474    12-01-2010 11:45
475    12-01-2010 11:45
476    12-01-2010 11:45
477    12-01-2010 11:45
478    12-01-2010 11:45
479    12-01-2010 11:45
480    12-01-2010 11:45
481    12-01-2010 11:45
482    12-01-2010 11:45
483    12-01-2010 11:45
484    12-01-2010 11:45
485    12-01-2010 11:45
486    12-01-2010 11:45
487    12-01-2010 11:45
488    12-01-2010 11:45
489    12-01-2010 11:45
490    12-01-2010 11:45
491    12-01-2010 11:45
492    12-01-2010 11:45
493    12-01-2010 11:45
494    12-01-2010 11:45
495    12-01-2010 11:45
496    12-01-2010 11:45
497    12-01-2010 11:45
498    12-01-2010 11:45
499    12-01-2010 11:45
500    12-01-2010 11:45
501    12-01-2010 11:45
502    12-01-2010 11:45
503    12-01-2010 11:45
504    12-01-2010 11:45
505    12-01-2010 11:45
506    12-01-2010 11:45
507    12-01-2010 11:45
508    12-01-2010 11:45
509    12-01-2010 11:45
510    12-01-2010 11:45
511    12-01-2010 11:45
512    12-01-2010 11:45
513    12-01-2010 11:45
514    12-01-2010 11:45
515    12-01-2010 11:45
516    12-01-2010 11:45
517    12-01-2010 11:45
518    12-01-2010 11:45
519    12-01-2010 11:45
520    12-01-2010 11:45
521    12-01-2010 11:45
522    12-01-2010 11:45
523    12-01-2010 11:45
524    12-01-2010 11:45
525    12-01-2010 11:45
526    12-01-2010 11:45
527    12-01-2010 11:45
528    12-01-2010 11:45
529    12-01-2010 11:45
530    12-01-2010 11:45
531    12-01-2010 11:45
Name: InvoiceDate, dtype: object
536412
532    12-01-2010 11:49
533    12-01-2010 11:49
534    12-01-2010 11:49
535    12-01-2010 11:49
536    12-01-2010 11:49
             ...
608    12-01-2010 11:49
609    12-01-2010 11:49
610    12-01-2010 11:49
611    12-01-2010 11:49
612    12-01-2010 11:49
Name: InvoiceDate, Length: 81, dtype: object
536415
613    12-01-2010 11:57
614    12-01-2010 11:57
615    12-01-2010 11:57
616    12-01-2010 11:57
617    12-01-2010 11:57
618    12-01-2010 11:57
619    12-01-2010 11:57
620    12-01-2010 11:57
621    12-01-2010 11:57
622    12-01-2010 11:57
623    12-01-2010 11:57
624    12-01-2010 11:57
625    12-01-2010 11:57
626    12-01-2010 11:57
627    12-01-2010 11:57
628    12-01-2010 11:57
629    12-01-2010 11:57
630    12-01-2010 11:57
631    12-01-2010 11:57
632    12-01-2010 11:57
633    12-01-2010 11:57
634    12-01-2010 11:57
635    12-01-2010 11:57
636    12-01-2010 11:57
637    12-01-2010 11:57
638    12-01-2010 11:57
639    12-01-2010 11:57
640    12-01-2010 11:57
641    12-01-2010 11:57
642    12-01-2010 11:57
643    12-01-2010 11:57
644    12-01-2010 11:57
645    12-01-2010 11:57
646    12-01-2010 11:57
647    12-01-2010 11:57
648    12-01-2010 11:57
649    12-01-2010 11:57
650    12-01-2010 11:57
651    12-01-2010 11:57
652    12-01-2010 11:57
653    12-01-2010 11:57
654    12-01-2010 11:57
655    12-01-2010 11:57
656    12-01-2010 11:57
657    12-01-2010 11:57
658    12-01-2010 11:57
659    12-01-2010 11:57
660    12-01-2010 11:57
661    12-01-2010 11:57
662    12-01-2010 11:57
663    12-01-2010 11:57
664    12-01-2010 11:57
665    12-01-2010 11:57
666    12-01-2010 11:57
667    12-01-2010 11:57
668    12-01-2010 11:57
669    12-01-2010 11:57
670    12-01-2010 11:57
671    12-01-2010 11:57
Name: InvoiceDate, dtype: object
536416
672    12-01-2010 11:58
673    12-01-2010 11:58
674    12-01-2010 11:58
675    12-01-2010 11:58
676    12-01-2010 11:58
677    12-01-2010 11:58
Name: InvoiceDate, dtype: object
536420
678    12-01-2010 12:03
679    12-01-2010 12:03
680    12-01-2010 12:03
681    12-01-2010 12:03
682    12-01-2010 12:03
683    12-01-2010 12:03
684    12-01-2010 12:03
685    12-01-2010 12:03
686    12-01-2010 12:03
687    12-01-2010 12:03
688    12-01-2010 12:03
689    12-01-2010 12:03
690    12-01-2010 12:03
691    12-01-2010 12:03
Name: InvoiceDate, dtype: object
536423
692    12-01-2010 12:08
693    12-01-2010 12:08
694    12-01-2010 12:08
695    12-01-2010 12:08
696    12-01-2010 12:08
697    12-01-2010 12:08
698    12-01-2010 12:08
699    12-01-2010 12:08
700    12-01-2010 12:08
Name: InvoiceDate, dtype: object
536425
701    12-01-2010 12:08
702    12-01-2010 12:08
703    12-01-2010 12:08
704    12-01-2010 12:08
705    12-01-2010 12:08
706    12-01-2010 12:08
707    12-01-2010 12:08
708    12-01-2010 12:08
709    12-01-2010 12:08
710    12-01-2010 12:08
711    12-01-2010 12:08
712    12-01-2010 12:08
713    12-01-2010 12:08
714    12-01-2010 12:08
715    12-01-2010 12:08
716    12-01-2010 12:08
717    12-01-2010 12:08
Name: InvoiceDate, dtype: object
536437
718    12-01-2010 12:12
719    12-01-2010 12:12
720    12-01-2010 12:12
721    12-01-2010 12:12
722    12-01-2010 12:12
723    12-01-2010 12:12
Name: InvoiceDate, dtype: object
536446
724    12-01-2010 12:15
725    12-01-2010 12:15
726    12-01-2010 12:15
727    12-01-2010 12:15
728    12-01-2010 12:15
729    12-01-2010 12:15
730    12-01-2010 12:15
731    12-01-2010 12:15
732    12-01-2010 12:15
733    12-01-2010 12:15
734    12-01-2010 12:15
735    12-01-2010 12:15
736    12-01-2010 12:15
737    12-01-2010 12:15
738    12-01-2010 12:15
739    12-01-2010 12:15
740    12-01-2010 12:15
741    12-01-2010 12:15
742    12-01-2010 12:15
743    12-01-2010 12:15
744    12-01-2010 12:15
745    12-01-2010 12:15
746    12-01-2010 12:15
747    12-01-2010 12:15
748    12-01-2010 12:15
749    12-01-2010 12:15
750    12-01-2010 12:15
751    12-01-2010 12:15
752    12-01-2010 12:15
753    12-01-2010 12:15
754    12-01-2010 12:15
755    12-01-2010 12:15
Name: InvoiceDate, dtype: object
536460
756    12-01-2010 12:22
757    12-01-2010 12:22
758    12-01-2010 12:22
759    12-01-2010 12:22
760    12-01-2010 12:22
761    12-01-2010 12:22
762    12-01-2010 12:22
763    12-01-2010 12:22
764    12-01-2010 12:22
765    12-01-2010 12:22
766    12-01-2010 12:22
767    12-01-2010 12:22
768    12-01-2010 12:22
769    12-01-2010 12:22
Name: InvoiceDate, dtype: object
536463
770    12-01-2010 12:22
Name: InvoiceDate, dtype: object
536464
771    12-01-2010 12:23
772    12-01-2010 12:23
773    12-01-2010 12:23
774    12-01-2010 12:23
775    12-01-2010 12:23
             ...
851    12-01-2010 12:23
852    12-01-2010 12:23
853    12-01-2010 12:23
854    12-01-2010 12:23
855    12-01-2010 12:23
Name: InvoiceDate, Length: 85, dtype: object
536466
856    12-01-2010 12:23
857    12-01-2010 12:23
Name: InvoiceDate, dtype: object
536477
858    12-01-2010 12:27
859    12-01-2010 12:27
860    12-01-2010 12:27
861    12-01-2010 12:27
862    12-01-2010 12:27
863    12-01-2010 12:27
864    12-01-2010 12:27
865    12-01-2010 12:27
866    12-01-2010 12:27
867    12-01-2010 12:27
868    12-01-2010 12:27
869    12-01-2010 12:27
870    12-01-2010 12:27
871    12-01-2010 12:27
Name: InvoiceDate, dtype: object
536488
872    12-01-2010 12:31
873    12-01-2010 12:31
874    12-01-2010 12:31
875    12-01-2010 12:31
876    12-01-2010 12:31
877    12-01-2010 12:31
878    12-01-2010 12:31
879    12-01-2010 12:31
880    12-01-2010 12:31
881    12-01-2010 12:31
882    12-01-2010 12:31
883    12-01-2010 12:31
884    12-01-2010 12:31
885    12-01-2010 12:31
886    12-01-2010 12:31
887    12-01-2010 12:31
888    12-01-2010 12:31
889    12-01-2010 12:31
890    12-01-2010 12:31
891    12-01-2010 12:31
892    12-01-2010 12:31
893    12-01-2010 12:31
894    12-01-2010 12:31
895    12-01-2010 12:31
896    12-01-2010 12:31
897    12-01-2010 12:31
898    12-01-2010 12:31
899    12-01-2010 12:31
900    12-01-2010 12:31
901    12-01-2010 12:31
902    12-01-2010 12:31
903    12-01-2010 12:31
904    12-01-2010 12:31
905    12-01-2010 12:31
906    12-01-2010 12:31
Name: InvoiceDate, dtype: object
536500
907    12-01-2010 12:35
908    12-01-2010 12:35
909    12-01-2010 12:35
910    12-01-2010 12:35
911    12-01-2010 12:35
912    12-01-2010 12:35
913    12-01-2010 12:35
914    12-01-2010 12:35
915    12-01-2010 12:35
916    12-01-2010 12:35
917    12-01-2010 12:35
918    12-01-2010 12:35
919    12-01-2010 12:35
920    12-01-2010 12:35
921    12-01-2010 12:35
Name: InvoiceDate, dtype: object
536502
922    12-01-2010 12:36
923    12-01-2010 12:36
924    12-01-2010 12:36
925    12-01-2010 12:36
926    12-01-2010 12:36
Name: InvoiceDate, dtype: object
536508
927    12-01-2010 12:38
928    12-01-2010 12:38
Name: InvoiceDate, dtype: object
536514
929    12-01-2010 12:40
930    12-01-2010 12:40
931    12-01-2010 12:40
932    12-01-2010 12:40
933    12-01-2010 12:40

5512    12-05-2010 11:57
5513    12-05-2010 11:57
5514    12-05-2010 11:57
5515    12-05-2010 11:57
5516    12-05-2010 11:57
              ...
5570    12-05-2010 11:57
5571    12-05-2010 11:57
5572    12-05-2010 11:57
5573    12-05-2010 11:57
5574    12-05-2010 11:57
Name: InvoiceDate, Length: 63, dtype: object
537067
5575    12-05-2010 11:57
5576    12-05-2010 11:57
5577    12-05-2010 11:57
5578    12-05-2010 11:57
5579    12-05-2010 11:57
5580    12-05-2010 11:57
Name: InvoiceDate, dtype: object
537077
5581    12-05-2010 11:59
5582    12-05-2010 11:59
5583    12-05-2010 11:59
5584    12-05-2010 11:59
5585    12-05-2010 11:59
5586    12-05-2010 11:59
5587    12-05-2010 11:59
5588    12-05-2010 11:59
5589    12-05-2010 11:59
5590    12-05-2010 11:59
5591    12-05-2010 11:59
5592    12-05-2010 11:59
5593    12-05-2010 11:59
5594    12-05-2010 11:59
5595    12-05-2010 11:59
5596    12-05-2010 11:59
5597    12-05-2010 11:59
5598    12-05-2010 11:59
5599    12-05-2010 11:59
5600    12-05-2010 11:59
5601    12-05-2010 11:59
5602    12-05-2010 11:59
5603    12-05-2010 11:59
5604    12-05-2010 11:59
5605    12-05-2010 11:59
5606    12-05-2010 11:59
Name: InvoiceDate, dtype: object
537081
5607    12-05-2010 12:00
5608    12-05-2010 12:00
5609    12-05-2010 12:00
5610    12-05-2010 12:00
5611    12-05-2010 12:00
5612    12-05-2010 12:00
5613    12-05-2010 12:00
5614    12-05-2010 12:00
5615    12-05-2010 12:00
5616    12-05-2010 12:00
5617    12-05-2010 12:00
5618    12-05-2010 12:00
5619    12-05-2010 12:00
5620    12-05-2010 12:00
5621    12-05-2010 12:00
5622    12-05-2010 12:00
5623    12-05-2010 12:00
5624    12-05-2010 12:00
5625    12-05-2010 12:00
5626    12-05-2010 12:00
5627    12-05-2010 12:00
5628    12-05-2010 12:00
5629    12-05-2010 12:00
5630    12-05-2010 12:00
5631    12-05-2010 12:00
Name: InvoiceDate, dtype: object
537086
5632    12-05-2010 12:01
5633    12-05-2010 12:01
5634    12-05-2010 12:01
5635    12-05-2010 12:01
5636    12-05-2010 12:01
5637    12-05-2010 12:01
5638    12-05-2010 12:01
5639    12-05-2010 12:01
Name: InvoiceDate, dtype: object
537090
5640    12-05-2010 12:02
Name: InvoiceDate, dtype: object
537111
5641    12-05-2010 12:08
5642    12-05-2010 12:08
5643    12-05-2010 12:08
5644    12-05-2010 12:08
5645    12-05-2010 12:08
5646    12-05-2010 12:08
5647    12-05-2010 12:08
5648    12-05-2010 12:08
5649    12-05-2010 12:08
5650    12-05-2010 12:08
5651    12-05-2010 12:08
5652    12-05-2010 12:08
5653    12-05-2010 12:08
5654    12-05-2010 12:08
5655    12-05-2010 12:08
5656    12-05-2010 12:08
5657    12-05-2010 12:08
5658    12-05-2010 12:08
5659    12-05-2010 12:08
5660    12-05-2010 12:08
5661    12-05-2010 12:08
5662    12-05-2010 12:08
5663    12-05-2010 12:08
Name: InvoiceDate, dtype: object
537117
5664    12-05-2010 12:09
Name: InvoiceDate, dtype: object
537126
5665    12-05-2010 12:13
5666    12-05-2010 12:13
5667    12-05-2010 12:13
5668    12-05-2010 12:13
5669    12-05-2010 12:13
              ...
5778    12-05-2010 12:13
5779    12-05-2010 12:13
5780    12-05-2010 12:13
5781    12-05-2010 12:13
5782    12-05-2010 12:13
Name: InvoiceDate, Length: 118, dtype: object
537127
5783    12-05-2010 12:13
5784    12-05-2010 12:13
Name: InvoiceDate, dtype: object
537128
5785    12-05-2010 12:15
5786    12-05-2010 12:15
5787    12-05-2010 12:15
5788    12-05-2010 12:15
5789    12-05-2010 12:15
5790    12-05-2010 12:15
5791    12-05-2010 12:15
5792    12-05-2010 12:15
5793    12-05-2010 12:15
5794    12-05-2010 12:15
5795    12-05-2010 12:15
5796    12-05-2010 12:15
5797    12-05-2010 12:15
5798    12-05-2010 12:15
5799    12-05-2010 12:15
5800    12-05-2010 12:15
5801    12-05-2010 12:15
5802    12-05-2010 12:15
5803    12-05-2010 12:15
5804    12-05-2010 12:15
5805    12-05-2010 12:15
5806    12-05-2010 12:15
5807    12-05-2010 12:15
Name: InvoiceDate, dtype: object
537129
5808    12-05-2010 12:15
5809    12-05-2010 12:15
5810    12-05-2010 12:15
5811    12-05-2010 12:15
5812    12-05-2010 12:15
5813    12-05-2010 12:15
5814    12-05-2010 12:15
5815    12-05-2010 12:15
5816    12-05-2010 12:15
5817    12-05-2010 12:15
5818    12-05-2010 12:15
5819    12-05-2010 12:15
5820    12-05-2010 12:15
5821    12-05-2010 12:15
5822    12-05-2010 12:15
5823    12-05-2010 12:15
5824    12-05-2010 12:15
Name: InvoiceDate, dtype: object
537130
5825    12-05-2010 12:23
5826    12-05-2010 12:23
5827    12-05-2010 12:23
5828    12-05-2010 12:23
5829    12-05-2010 12:23
5830    12-05-2010 12:23
5831    12-05-2010 12:23
5832    12-05-2010 12:23
5833    12-05-2010 12:23
5834    12-05-2010 12:23
5835    12-05-2010 12:23
5836    12-05-2010 12:23
5837    12-05-2010 12:23
5838    12-05-2010 12:23
5839    12-05-2010 12:23
5840    12-05-2010 12:23
5841    12-05-2010 12:23
5842    12-05-2010 12:23
5843    12-05-2010 12:23
Name: InvoiceDate, dtype: object
537131
5844    12-05-2010 12:26
5845    12-05-2010 12:26
5846    12-05-2010 12:26
5847    12-05-2010 12:26
5848    12-05-2010 12:26
5849    12-05-2010 12:26
5850    12-05-2010 12:26
5851    12-05-2010 12:26
5852    12-05-2010 12:26
5853    12-05-2010 12:26
5854    12-05-2010 12:26
5855    12-05-2010 12:26
5856    12-05-2010 12:26
5857    12-05-2010 12:26
5858    12-05-2010 12:26
5859    12-05-2010 12:26
5860    12-05-2010 12:26
5861    12-05-2010 12:26
5862    12-05-2010 12:26
5863    12-05-2010 12:26
5864    12-05-2010 12:26
5865    12-05-2010 12:26
5866    12-05-2010 12:26
5867    12-05-2010 12:26
5868    12-05-2010 12:26
5869    12-05-2010 12:26
5870    12-05-2010 12:26
5871    12-05-2010 12:26
5872    12-05-2010 12:26
5873    12-05-2010 12:26
5874    12-05-2010 12:26
5875    12-05-2010 12:26
5876    12-05-2010 12:26
5877    12-05-2010 12:26
5878    12-05-2010 12:26
5879    12-05-2010 12:26
5880    12-05-2010 12:26
5881    12-05-2010 12:26
Name: InvoiceDate, dtype: object
537133
5882    12-05-2010 12:29
5883    12-05-2010 12:29
5884    12-05-2010 12:29
5885    12-05-2010 12:29
5886    12-05-2010 12:29
5887    12-05-2010 12:29
5888    12-05-2010 12:29
5889    12-05-2010 12:29
5890    12-05-2010 12:29
5891    12-05-2010 12:29
5892    12-05-2010 12:29
5893    12-05-2010 12:29
5894    12-05-2010 12:29
5895    12-05-2010 12:29
5896    12-05-2010 12:29
5897    12-05-2010 12:29
5898    12-05-2010 12:29
5899    12-05-2010 12:29
5900    12-05-2010 12:29
5901    12-05-2010 12:29
5902    12-05-2010 12:29
5903    12-05-2010 12:29
5904    12-05-2010 12:29
5905    12-05-2010 12:29
5906    12-05-2010 12:29
5907    12-05-2010 12:29
5908    12-05-2010 12:29
5909    12-05-2010 12:29
5910    12-05-2010 12:29
5911    12-05-2010 12:29
5912    12-05-2010 12:29
5913    12-05-2010 12:29
5914    12-05-2010 12:29
5915    12-05-2010 12:29
5916    12-05-2010 12:29
5917    12-05-2010 12:29
5918    12-05-2010 12:29
5919    12-05-2010 12:29
5920    12-05-2010 12:29
5921    12-05-2010 12:29
5922    12-05-2010 12:29
5923    12-05-2010 12:29
5924    12-05-2010 12:29
5925    12-05-2010 12:29
5926    12-05-2010 12:29
5927    12-05-2010 12:29
5928    12-05-2010 12:29
5929    12-05-2010 12:29
5930    12-05-2010 12:29
5931    12-05-2010 12:29
5932    12-05-2010 12:29
5933    12-05-2010 12:29
5934    12-05-2010 12:29
5935    12-05-2010 12:29
5936    12-05-2010 12:29
Name: InvoiceDate, dtype: object
537134
5937    12-05-2010 12:34
5938    12-05-2010 12:34
5939    12-05-2010 12:34
5940    12-05-2010 12:34
5941    12-05-2010 12:34
5942    12-05-2010 12:34
5943    12-05-2010 12:34
5944    12-05-2010 12:34
5945    12-05-2010 12:34
Name: InvoiceDate, dtype: object
537135
5946    12-05-2010 12:35
5947    12-05-2010 12:35
5948    12-05-2010 12:35
5949    12-05-2010 12:35
5950    12-05-2010 12:35
              ...
6058    12-05-2010 12:35
6059    12-05-2010 12:35
6060    12-05-2010 12:35
6061    12-05-2010 12:35
6062    12-05-2010 12:35
Name: InvoiceDate, Length: 117, dtype: object
537136
6063    12-05-2010 12:42
6064    12-05-2010 12:42
6065    12-05-2010 12:42
6066    12-05-2010 12:42
6067    12-05-2010 12:42
6068    12-05-2010 12:42
6069    12-05-2010 12:42
6070    12-05-2010 12:42
6071    12-05-2010 12:42
6072    12-05-2010 12:42
6073    12-05-2010 12:42
6074    12-05-2010 12:42
6075    12-05-2010 12:42
6076    12-05-2010 12:42
6077    12-05-2010 12:42
6078    12-05-2010 12:42
6079    12-05-2010 12:42
6080    12-05-2010 12:42
6081    12-05-2010 12:42
6082    12-05-2010 12:42
6083    12-05-2010 12:42
6084    12-05-2010 12:42
6085    12-05-2010 12:42
6086    12-05-2010 12:42
6087    12-05-2010 12:42
6088    12-05-2010 12:42
6089    12-05-2010 12:42
6090    12-05-2010 12:42
6091    12-05-2010 12:42
6092    12-05-2010 12:42
6093    12-05-2010 12:42
6094    12-05-2010 12:42
6095    12-05-2010 12:42
6096    12-05-2010 12:42
6097    12-05-2010 12:42
6098    12-05-2010 12:42
6099    12-05-2010 12:42
Name: InvoiceDate, dtype: object
537137
6100    12-05-2010 12:43
6101    12-05-2010 12:43
6102    12-05-2010 12:43
6103    12-05-2010 12:43
6104    12-05-2010 12:43
              ...
6161    12-05-2010 12:43
6162    12-05-2010 12:43
6163    12-05-2010 12:43
6164    12-05-2010 12:43
6165    12-05-2010 12:43
Name: InvoiceDate, Length: 66, dtype: object
537138
6166    12-05-2010 12:44
6167    12-05-2010 12:44
6168    12-05-2010 12:44
6169    12-05-2010 12:44
6170    12-05-2010 12:44
6171    12-05-2010 12:44
6172    12-05-2010 12:44
6173    12-05-2010 12:44
6174    12-05-2010 12:44
6175    12-05-2010 12:44
6176    12-05-2010 12:44
6177    12-05-2010 12:44
6178    12-05-2010 12:44
6179    12-05-2010 12:44
6180    12-05-2010 12:44
6181    12-05-2010 12:44
6182    12-05-2010 12:44
6183    12-05-2010 12:44
6184    12-05-2010 12:44
6185    12-05-2010 12:44
6186    12-05-2010 12:44
6187    12-05-2010 12:44
6188    12-05-2010 12:44
6189    12-05-2010 12:44
6190    12-05-2010 12:44
6191    12-05-2010 12:44
6192    12-05-2010 12:44
6193    12-05-2010 12:44
6194    12-05-2010 12:44
6195    12-05-2010 12:44
6196    12-05-2010 12:44
6197    12-05-2010 12:44
6198    12-05-2010 12:44
Name: InvoiceDate, dtype: object
537139
6199    12-05-2010 12:47
6200    12-05-2010 12:47
6201    12-05-2010 12:47
Name: InvoiceDate, dtype: object
537140
6202    12-05-2010 12:53
6203    12-05-2010 12:53
6204    12-05-2010 12:53
6205    12-05-2010 12:53
6206    12-05-2010 12:53
6207    12-05-2010 12:53
6208    12-05-2010 12:53
6209    12-05-2010 12:53
6210    12-05-2010 12:53
6211    12-05-2010 12:53
6212    12-05-2010 12:53
6213    12-05-2010 12:53
6214    12-05-2010 12:53
6215    12-05-2010 12:53
6216    12-05-2010 12:53
6217    12-05-2010 12:53
6218    12-05-2010 12:53
6219    12-05-2010 12:53
6220    12-05-2010 12:53
6221    12-05-2010 12:53
6222    12-05-2010 12:53
6223    12-05-2010 12:53
6224    12-05-2010 12:53
6225    12-05-2010 12:53
6226    12-05-2010 12:53
6227    12-05-2010 12:53
6228    12-05-2010 12:53
6229    12-05-2010 12:53
6230    12-05-2010 12:53
6231    12-05-2010 12:53
6232    12-05-2010 12:53
6233    12-05-2010 12:53
6234    12-05-2010 12:53
6235    12-05-2010 12:53
6236    12-05-2010 12:53
6237    12-05-2010 12:53
6238    12-05-2010 12:53
6239    12-05-2010 12:53
6240    12-05-2010 12:53
Name: InvoiceDate, dtype: object
537141
6241    12-05-2010 12:57
6242    12-05-2010 12:57
6243    12-05-2010 12:57
6244    12-05-2010 12:57
6245    12-05-2010 12:57
6246    12-05-2010 12:57
6247    12-05-2010 12:57
6248    12-05-2010 12:57
6249    12-05-2010 12:57
6250    12-05-2010 12:57
6251    12-05-2010 12:57
6252    12-05-2010 12:57
6253    12-05-2010 12:57
6254    12-05-2010 12:57
6255    12-05-2010 12:57
6256    12-05-2010 12:57
6257    12-05-2010 12:57
6258    12-05-2010 12:57
6259    12-05-2010 12:57
6260    12-05-2010 12:57
6261    12-05-2010 12:57
6262    12-05-2010 12:57
6263    12-05-2010 12:57
6264    12-05-2010 12:57
6265    12-05-2010 12:57
6266    12-05-2010 12:57
6267    12-05-2010 12:57
6268    12-05-2010 12:57
6269    12-05-2010 12:57
6270    12-05-2010 12:57
6271    12-05-2010 12:57
6272    12-05-2010 12:57
6273    12-05-2010 12:57
6274    12-05-2010 12:57
6275    12-05-2010 12:57
6276    12-05-2010 12:57
6277    12-05-2010 12:57
6278    12-05-2010 12:57
6279    12-05-2010 12:57
6280    12-05-2010 12:57
6281    12-05-2010 12:57
6282    12-05-2010 12:57
6283    12-05-2010 12:57
6284    12-05-2010 12:57
Name: InvoiceDate, dtype: object
537142
6285    12-05-2010 12:57
6286    12-05-2010 12:57
6287    12-05-2010 12:57
6288    12-05-2010 12:57
6289    12-05-2010 12:57
6290    12-05-2010 12:57
6291    12-05-2010 12:57
6292    12-05-2010 12:57
6293    12-05-2010 12:57
6294    12-05-2010 12:57
6295    12-05-2010 12:57
6296    12-05-2010 12:57
6297    12-05-2010 12:57
6298    12-05-2010 12:57
6299    12-05-2010 12:57
Name: InvoiceDate, dtype: object
537144
6300    12-05-2010 13:00
6301    12-05-2010 13:00
6302    12-05-2010 13:00
6303    12-05-2010 13:00
6304    12-05-2010 13:00
              ...
6400    12-05-2010 13:00
6401    12-05-2010 13:00
6402    12-05-2010 13:00
6403    12-05-2010 13:00
6404    12-05-2010 13:00
Name: InvoiceDate, Length: 105, dtype: object
537153
6405    12-05-2010 13:03
6406    12-05-2010 13:03
6407    12-05-2010 13:03
6408    12-05-2010 13:03
6409    12-05-2010 13:03
6410    12-05-2010 13:03
6411    12-05-2010 13:03
6412    12-05-2010 13:03
6413    12-05-2010 13:03
6414    12-05-2010 13:03
6415    12-05-2010 13:03
6416    12-05-2010 13:03
6417    12-05-2010 13:03
6418    12-05-2010 13:03
6419    12-05-2010 13:03
6420    12-05-2010 13:03
6421    12-05-2010 13:03
6422    12-05-2010 13:03
6423    12-05-2010 13:03
6424    12-05-2010 13:03
6425    12-05-2010 13:03
6426    12-05-2010 13:03
6427    12-05-2010 13:03
6428    12-05-2010 13:03
6429    12-05-2010 13:03
6430    12-05-2010 13:03
6431    12-05-2010 13:03
6432    12-05-2010 13:03
6433    12-05-2010 13:03
6434    12-05-2010 13:03
6435    12-05-2010 13:03
6436    12-05-2010 13:03
6437    12-05-2010 13:03
6438    12-05-2010 13:03
6439    12-05-2010 13:03
6440    12-05-2010 13:03
6441    12-05-2010 13:03
6442    12-05-2010 13:03
6443    12-05-2010 13:03
6444    12-05-2010 13:03
6445    12-05-2010 13:03
6446    12-05-2010 13:03
6447    12-05-2010 13:03
6448    12-05-2010 13:03
6449    12-05-2010 13:03
Name: InvoiceDate, dtype: object
537154
6450    12-05-2010 13:05
6451    12-05-2010 13:05
6452    12-05-2010 13:05
6453    12-05-2010 13:05
6454    12-05-2010 13:05
              ...
6509    12-05-2010 13:05
6510    12-05-2010 13:05
6511    12-05-2010 13:05
6512    12-05-2010 13:05
6513    12-05-2010 13:05
Name: InvoiceDate, Length: 64, dtype: object
537155
6514    12-05-2010 13:05
6515    12-05-2010 13:05
6516    12-05-2010 13:05
6517    12-05-2010 13:05
6518    12-05-2010 13:05
6519    12-05-2010 13:05
6520    12-05-2010 13:05
6521    12-05-2010 13:05
6522    12-05-2010 13:05
6523    12-05-2010 13:05
6524    12-05-2010 13:05
6525    12-05-2010 13:05
6526    12-05-2010 13:05
6527    12-05-2010 13:05
6528    12-05-2010 13:05
6529    12-05-2010 13:05
6530    12-05-2010 13:05
6531    12-05-2010 13:05
6532    12-05-2010 13:05
6533    12-05-2010 13:05
6534    12-05-2010 13:05
6535    12-05-2010 13:05
6536    12-05-2010 13:05
6537    12-05-2010 13:05
6538    12-05-2010 13:05
6539    12-05-2010 13:05
6540    12-05-2010 13:05
6541    12-05-2010 13:05
6542    12-05-2010 13:05
6543    12-05-2010 13:05
6544    12-05-2010 13:05
6545    12-05-2010 13:05
6546    12-05-2010 13:05
Name: InvoiceDate, dtype: object
537156
6547    12-05-2010 13:08
6548    12-05-2010 13:08
6549    12-05-2010 13:08
6550    12-05-2010 13:08
6551    12-05-2010 13:08
6552    12-05-2010 13:08
6553    12-05-2010 13:08
6554    12-05-2010 13:08
6555    12-05-2010 13:08
6556    12-05-2010 13:08
6557    12-05-2010 13:08
6558    12-05-2010 13:08
6559    12-05-2010 13:08
6560    12-05-2010 13:08
6561    12-05-2010 13:08
6562    12-05-2010 13:08
6563    12-05-2010 13:08
6564    12-05-2010 13:08
6565    12-05-2010 13:08
Name: InvoiceDate, dtype: object
537158
6566    12-05-2010 13:10
6567    12-05-2010 13:10
6568    12-05-2010 13:10
6569    12-05-2010 13:10
6570    12-05-2010 13:10
6571    12-05-2010 13:10
6572    12-05-2010 13:10
6573    12-05-2010 13:10
6574    12-05-2010 13:10
6575    12-05-2010 13:10
Name: InvoiceDate, dtype: object
537159
6576    12-05-2010 13:17
6577    12-05-2010 13:17
6578    12-05-2010 13:17
6579    12-05-2010 13:17
6580    12-05-2010 13:17
6581    12-05-2010 13:17
6582    12-05-2010 13:17
6583    12-05-2010 13:17
6584    12-05-2010 13:17
6585    12-05-2010 13:17
6586    12-05-2010 13:17
6587    12-05-2010 13:17
6588    12-05-2010 13:17
6589    12-05-2010 13:17
6590    12-05-2010 13:17
6591    12-05-2010 13:17
6592    12-05-2010 13:17
6593    12-05-2010 13:17
6594    12-05-2010 13:17
6595    12-05-2010 13:17
6596    12-05-2010 13:17
6597    12-05-2010 13:17
6598    12-05-2010 13:17
6599    12-05-2010 13:17
6600    12-05-2010 13:17
6601    12-05-2010 13:17
6602    12-05-2010 13:17
6603    12-05-2010 13:17
Name: InvoiceDate, dtype: object
537160
6604    12-05-2010 13:18
6605    12-05-2010 13:18
6606    12-05-2010 13:18
6607    12-05-2010 13:18
6608    12-05-2010 13:18
6609    12-05-2010 13:18
6610    12-05-2010 13:18
6611    12-05-2010 13:18
6612    12-05-2010 13:18
6613    12-05-2010 13:18
6614    12-05-2010 13:18
6615    12-05-2010 13:18
6616    12-05-2010 13:18
6617    12-05-2010 13:18
6618    12-05-2010 13:18
6619    12-05-2010 13:18
6620    12-05-2010 13:18
6621    12-05-2010 13:18
6622    12-05-2010 13:18
6623    12-05-2010 13:18
6624    12-05-2010 13:18
6625    12-05-2010 13:18
6626    12-05-2010 13:18
6627    12-05-2010 13:18
6628    12-05-2010 13:18
6629    12-05-2010 13:18
Name: InvoiceDate, dtype: object
537163
6630    12-05-2010 13:21
6631    12-05-2010 13:21
6632    12-05-2010 13:21
6633    12-05-2010 13:21
6634    12-05-2010 13:21
6635    12-05-2010 13:21
6636    12-05-2010 13:21
6637    12-05-2010 13:21
6638    12-05-2010 13:21
6639    12-05-2010 13:21
6640    12-05-2010 13:21
6641    12-05-2010 13:21
6642    12-05-2010 13:21
6643    12-05-2010 13:21
6644    12-05-2010 13:21
6645    12-05-2010 13:21
6646    12-05-2010 13:21
6647    12-05-2010 13:21
6648    12-05-2010 13:21
6649    12-05-2010 13:21
6650    12-05-2010 13:21
Name: InvoiceDate, dtype: object
537176
6651    12-05-2010 13:26
6652    12-05-2010 13:26
6653    12-05-2010 13:26
6654    12-05-2010 13:26
6655    12-05-2010 13:26
6656    12-05-2010 13:26
6657    12-05-2010 13:26
6658    12-05-2010 13:26
6659    12-05-2010 13:26
6660    12-05-2010 13:26
6661    12-05-2010 13:26
6662    12-05-2010 13:26
6663    12-05-2010 13:26
6664    12-05-2010 13:26
6665    12-05-2010 13:26
6666    12-05-2010 13:26
6667    12-05-2010 13:26
6668    12-05-2010 13:26
6669    12-05-2010 13:26
6670    12-05-2010 13:26
6671    12-05-2010 13:26
Name: InvoiceDate, dtype: object
537179
6672    12-05-2010 13:29
6673    12-05-2010 13:29
6674    12-05-2010 13:29
6675    12-05-2010 13:29
6676    12-05-2010 13:29
6677    12-05-2010 13:29
6678    12-05-2010 13:29
6679    12-05-2010 13:29
6680    12-05-2010 13:29
6681    12-05-2010 13:29
6682    12-05-2010 13:29
6683    12-05-2010 13:29
6684    12-05-2010 13:29
Name: InvoiceDate, dtype: object
537192
6685    12-05-2010 13:42
6686    12-05-2010 13:42
6687    12-05-2010 13:42
6688    12-05-2010 13:42
6689    12-05-2010 13:42
6690    12-05-2010 13:42
6691    12-05-2010 13:42
6692    12-05-2010 13:42
6693    12-05-2010 13:42
6694    12-05-2010 13:42
6695    12-05-2010 13:42
6696    12-05-2010 13:42
6697    12-05-2010 13:42
6698    12-05-2010 13:42
6699    12-05-2010 13:42
6700    12-05-2010 13:42
6701    12-05-2010 13:42
6702    12-05-2010 13:42
6703    12-05-2010 13:42
6704    12-05-2010 13:42
6705    12-05-2010 13:42
6706    12-05-2010 13:42
6707    12-05-2010 13:42
6708    12-05-2010 13:42
6709    12-05-2010 13:42
6710    12-05-2010 13:42
6711    12-05-2010 13:42
6712    12-05-2010 13:42
6713    12-05-2010 13:42
6714    12-05-2010 13:42
6715    12-05-2010 13:42
6716    12-05-2010 13:42
6717    12-05-2010 13:42
6718    12-05-2010 13:42
6719    12-05-2010 13:42
6720    12-05-2010 13:42

In [10]:
 df_2010["bill_for_product"] = df_2010["Quantity"]*df_2010["UnitPrice"] # adding product total (7)

In [11]:
df_2010

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
17410,538529,21733,RED HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290.0,United Kingdom,35.40
17411,538529,21741,COSY SLIPPER SHOES LARGE GREEN,6,12/13/2010 10:24,2.95,14290.0,United Kingdom,17.70
17412,538529,21485,RETROSPOT HEART HOT WATER BOTTLE,6,12/13/2010 10:24,4.95,14290.0,United Kingdom,29.70
17413,538529,22112,CHOCOLATE HOT WATER BOTTLE,12,12/13/2010 10:24,4.95,14290.0,United Kingdom,59.40
17414,538529,22835,HOT WATER BOTTLE I AM SO POORLY,4,12/13/2010 10:24,4.65,14290.0,United Kingdom,18.60

In [12]:
# money spend per cart (8)
df_2010.groupby("InvoiceNo")["bill_for_product"].sum()

InvoiceNo
536365     139.12
536366      22.20
536367     278.73
536368      70.05
536369      17.85
           ...
538525     881.01
538526    1206.72
538527     418.92
538528     103.50
538529     451.50
Name: bill_for_product, Length: 899, dtype: float64

In [13]:
#avg cart value (9)
cart_total = df_2010.groupby("InvoiceNo")["bill_for_product"].sum()
#cart_total.mean
display(cart_total)

InvoiceNo
536365     139.12
536366      22.20
536367     278.73
536368      70.05
536369      17.85
           ...
538525     881.01
538526    1206.72
538527     418.92
538528     103.50
538529     451.50
Name: bill_for_product, Length: 899, dtype: float64

In [14]:
#how many unique items are there in total (10)
len(df_2010.groupby("StockCode").count())

2118

In [15]:
# how many invoices per customer (11)
df_2010.groupby("CustomerID")["InvoiceNo"].count()

CustomerID
12347.0    31
12386.0     8
12395.0    12
12427.0    10
12429.0    20
           ..
18225.0     2
18229.0    10
18239.0    29
18259.0     7
18269.0     7
Name: InvoiceNo, Length: 650, dtype: int64

In [16]:
#how much value spend by per customer (12)
df_2010.groupby("CustomerID").bill_for_product.sum()

CustomerID
12347.0     711.79
12386.0     258.90
12395.0     346.10
12427.0     303.50
12429.0    1281.50
            ...
18225.0      30.00
18229.0     653.20
18239.0     438.10
18259.0     376.30
18269.0     168.60
Name: bill_for_product, Length: 650, dtype: float64

In [17]:
df_2010.dtypes #changing dtype from float to int64 (13)

InvoiceNo             int64
StockCode            object
Description          object
Quantity              int64
InvoiceDate          object
UnitPrice           float64
CustomerID          float64
Country              object
bill_for_product    float64
dtype: object

In [18]:
df_2010 = df_2010.astype({"CustomerID":'int64'})

In [19]:
df_2010

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
17410,538529,21733,RED HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290,United Kingdom,35.40
17411,538529,21741,COSY SLIPPER SHOES LARGE GREEN,6,12/13/2010 10:24,2.95,14290,United Kingdom,17.70
17412,538529,21485,RETROSPOT HEART HOT WATER BOTTLE,6,12/13/2010 10:24,4.95,14290,United Kingdom,29.70
17413,538529,22112,CHOCOLATE HOT WATER BOTTLE,12,12/13/2010 10:24,4.95,14290,United Kingdom,59.40
17414,538529,22835,HOT WATER BOTTLE I AM SO POORLY,4,12/13/2010 10:24,4.65,14290,United Kingdom,18.60

In [20]:
hel=df_2010.groupby("Country")["Country"].count().sort_values(ascending=0).head(5) #top 5 country who do online shopping (14)
dft = pd.DataFrame(hel)
dft.to_csv("temp.csv")

In [21]:
hel=df_2010["Country"].value_counts().head(5)
hel

Country
United Kingdom    16081
Germany             287
France              284
EIRE                215
Norway              147
Name: count, dtype: int64

In [22]:
country_2010 = df_2010.groupby(["Country"])["Country"].count().reset_index(name='Count').sort_values(["Count"],ascending=0)
country_2011 = df_2011.groupby("Country")["Country"].count().sort_values(ascending=0).head(5)
country_2010

            Country  Count
17   United Kingdom  16081
6           Germany    287
5            France    284
4              EIRE    215
12           Norway    147
14         Portugal     94
15            Spain     65
9             Japan     65
10        Lithuania     35
7           Iceland     31
8             Italy     24
0         Australia     22
3           Denmark     20
2   Channel Islands     17
1           Belgium     12
13           Poland      8
16      Switzerland      6
11      Netherlands      2

In [24]:
#df = df.groupby(['Name'])['age'].count().reset_index(name='Count').sort_values(['Count'], ascending=True)

In [25]:
 #top10 people who spend the most  (15)

In [26]:
most_values_customers = df_2010.groupby("CustomerID")["bill_for_product"].sum().sort_values(ascending=0)

In [27]:
mini_df = pd.DataFrame(most_values_customers)
mini_df.columns =['CustomerID and Total spendings']

In [28]:
most_values_customers.head(10)

CustomerID
18102    27834.61
15061    17344.78
13777     6840.16
14911     5567.63
17850     5391.21
16210     5277.74
16029     4271.52
13798     4170.66
12755     3794.40
12433     3787.12
Name: bill_for_product, dtype: float64

In [29]:
df_2010.head(23)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12-01-2010 08:26,7.65,17850,United Kingdom,15.30
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12-01-2010 08:26,4.25,17850,United Kingdom,25.50
7,536366,22633,HAND WARMER UNION JACK,6,12-01-2010 08:28,1.85,17850,United Kingdom,11.10
8,536366,22632,HAND WARMER RED POLKA DOT,6,12-01-2010 08:28,1.85,17850,United Kingdom,11.10
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12-01-2010 08:34,1.69,13047,United Kingdom,54.08
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12-01-2010 08:34,2.10,13047,United Kingdom,12.60
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12-01-2010 08:34,2.10,13047,United Kingdom,12.60
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12-01-2010 08:34,3.75,13047,United Kingdom,30.00
13,536367,22310,IVORY KNITTED MUG COSY,6,12-01-2010 08:34,1.65,13047,United Kingdom,9.90
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12-01-2010 08:34,4.25,13047,United Kingdom,25.50
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12-01-2010 08:34,4.95,13047,United Kingdom,14.85
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12-01-2010 08:34,9.95,13047,United Kingdom,19.90
17,536367,21754,HOME BUILDING BLOCK WORD,3,12-01-2010 08:34,5.95,13047,United Kingdom,17.85
18,536367,21755,LOVE BUILDING BLOCK WORD,3,12-01-2010 08:34,5.95,13047,United Kingdom,17.85
19,536367,21777,RECIPE BOX WITH METAL HEART,4,12-01-2010 08:34,7.95,13047,United Kingdom,31.80
20,536367,48187,DOORMAT NEW ENGLAND,4,12-01-2010 08:34,7.95,13047,United Kingdom,31.80
21,536368,22960,JAM MAKING SET WITH JARS,6,12-01-2010 08:34,4.25,13047,United Kingdom,25.50
22,536368,22913,RED COAT RACK PARIS FASHION,3,12-01-2010 08:34,4.95,13047,United Kingdom,14.85

In [30]:
#top 10 selling items (16)
df_2010.groupby("Description")["Description"].count().sort_values(ascending=0).head(10)

Description
WHITE HANGING HEART T-LIGHT HOLDER    131
PAPER CHAIN KIT 50'S CHRISTMAS        114
HAND WARMER BIRD DESIGN                92
RED WOOLLY HOTTIE WHITE HEART.         89
HAND WARMER UNION JACK                 86
PAPER CHAIN KIT VINTAGE CHRISTMAS      85
REGENCY CAKESTAND 3 TIER               84
SCOTTIE DOG HOT WATER BOTTLE           79
HAND WARMER SCOTTY DOG DESIGN          77
JAM MAKING SET PRINTED                 75
Name: Description, dtype: int64

In [31]:
#top 10 least selling items (17)
df_2010.groupby("Description")["Description"].count().sort_values(ascending=0).tail(10)

Description
SET/4 BLUE FLOWER CANDLES IN BOWL      1
PAIR PADDED HANGERS PINK CHECK         1
BLUE SCANDINAVIAN PAISLEY WRAP         1
SET/3 TALL GLASS CANDLE HOLDER PINK    1
BLUE SHARK HELICOPTER                  1
SET/3 FLORAL GARDEN TOOLS IN BAG       1
BLUE TILED TRAY                        1
BLUE TRAVEL FIRST AID KIT              1
BLUE WIRE SPIRAL CANDLE HOLDER         1
HEN HOUSE W CHICK STANDING             1
Name: Description, dtype: int64

In [32]:
df_2010

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
17410,538529,21733,RED HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290,United Kingdom,35.40
17411,538529,21741,COSY SLIPPER SHOES LARGE GREEN,6,12/13/2010 10:24,2.95,14290,United Kingdom,17.70
17412,538529,21485,RETROSPOT HEART HOT WATER BOTTLE,6,12/13/2010 10:24,4.95,14290,United Kingdom,29.70
17413,538529,22112,CHOCOLATE HOT WATER BOTTLE,12,12/13/2010 10:24,4.95,14290,United Kingdom,59.40
17414,538529,22835,HOT WATER BOTTLE I AM SO POORLY,4,12/13/2010 10:24,4.65,14290,United Kingdom,18.60

In [33]:
def am_pm(str):
    judge = ""
    flag = 0
    for chr in str:
        if chr==":":
            break
        if flag==1:
            judge+=chr
        if chr == " ":
            flag=1;
    return judge

In [34]:
timee = df_2010["InvoiceDate"].map(lambda x:am_pm(x)) # for how much time the users were most active (18)

len(timee.groupby(timee).count())

15

In [35]:
timee.groupby(timee).count().sort_values(ascending=0)

InvoiceDate
12    3589
13    2800
11    2560
14    2045
15    1937
10    1607
16    1183
09     631
17     417
19     173
18     165
08     149
9       84
20      65
07      10
Name: InvoiceDate, dtype: int64

In [36]:
df_2010

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
17410,538529,21733,RED HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290,United Kingdom,35.40
17411,538529,21741,COSY SLIPPER SHOES LARGE GREEN,6,12/13/2010 10:24,2.95,14290,United Kingdom,17.70
17412,538529,21485,RETROSPOT HEART HOT WATER BOTTLE,6,12/13/2010 10:24,4.95,14290,United Kingdom,29.70
17413,538529,22112,CHOCOLATE HOT WATER BOTTLE,12,12/13/2010 10:24,4.95,14290,United Kingdom,59.40
17414,538529,22835,HOT WATER BOTTLE I AM SO POORLY,4,12/13/2010 10:24,4.65,14290,United Kingdom,18.60

In [37]:
# on which date most orders were placed (19df_)
def dts(str):
    day = ""
    flag = 0
    for chr in str:
        if flag==1 and (chr=='/' or chr=='-'):
            break
        if flag==1:
            day+=chr
        if chr == '/' or chr=='-':
            flag=1
            
    return day

In [38]:
day = df_2010["InvoiceDate"].map(lambda x:dts(x)) # for how much time the users were most active
timee.groupby(day).count().sort_values(ascending=0)

InvoiceDate
05    2708
02    2000
08    1948
06    1945
01    1942
09    1749
12    1436
10    1380
07    1110
03    1103
13      94
Name: InvoiceDate, dtype: int64

In [39]:
df_2010

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
17410,538529,21733,RED HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290,United Kingdom,35.40
17411,538529,21741,COSY SLIPPER SHOES LARGE GREEN,6,12/13/2010 10:24,2.95,14290,United Kingdom,17.70
17412,538529,21485,RETROSPOT HEART HOT WATER BOTTLE,6,12/13/2010 10:24,4.95,14290,United Kingdom,29.70
17413,538529,22112,CHOCOLATE HOT WATER BOTTLE,12,12/13/2010 10:24,4.95,14290,United Kingdom,59.40
17414,538529,22835,HOT WATER BOTTLE I AM SO POORLY,4,12/13/2010 10:24,4.65,14290,United Kingdom,18.60

In [40]:
# monthly sales of our data set
def mth(str):
    day = ""
    flag = 0
    for chr in str:
        if chr == '/' or chr=='-':
            break
        day+=chr
        
            
    return day

In [41]:
month = df_2010["InvoiceDate"].map(lambda x:mth(x))

In [59]:
month #but only one month found

0        12
1        12
2        12
3        12
4        12
         ..
17410    12
17411    12
17412    12
17413    12
17414    12
Name: InvoiceDate, Length: 17415, dtype: object

In [43]:
df_2010

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
17410,538529,21733,RED HANGING HEART T-LIGHT HOLDER,12,12/13/2010 10:24,2.95,14290,United Kingdom,35.40
17411,538529,21741,COSY SLIPPER SHOES LARGE GREEN,6,12/13/2010 10:24,2.95,14290,United Kingdom,17.70
17412,538529,21485,RETROSPOT HEART HOT WATER BOTTLE,6,12/13/2010 10:24,4.95,14290,United Kingdom,29.70
17413,538529,22112,CHOCOLATE HOT WATER BOTTLE,12,12/13/2010 10:24,4.95,14290,United Kingdom,59.40
17414,538529,22835,HOT WATER BOTTLE I AM SO POORLY,4,12/13/2010 10:24,4.65,14290,United Kingdom,18.60

In [44]:
ne = df_2010["Quantity"].value_counts().sum()
print(ne)

17415

In [45]:
len(df_2010["InvoiceNo"].unique())

899

In [46]:
ne

17415

In [47]:
df_2010["bill_for_product"].sum()

367158.85

In [48]:
df_2010.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,bill_for_product
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850,United Kingdom,20.34

In [64]:
df_2010.groupby("Description")["Quantity"].count().sort_values(ascending=False)

Description
WHITE HANGING HEART T-LIGHT HOLDER    131
PAPER CHAIN KIT 50'S CHRISTMAS        114
HAND WARMER BIRD DESIGN                92
RED WOOLLY HOTTIE WHITE HEART.         89
HAND WARMER UNION JACK                 86
                                     ...
SET/3 FLORAL GARDEN TOOLS IN BAG        1
BLUE TILED TRAY                         1
BLUE TRAVEL FIRST AID KIT               1
BLUE WIRE SPIRAL CANDLE HOLDER          1
HEN HOUSE W CHICK STANDING              1
Name: Quantity, Length: 2123, dtype: int64

In [55]:
df_2010["StockCode"].value_counts().sum()

17415

In [56]:
df_2010["CustomerID"].value_counts()

CustomerID
12748    544
17850    297
14911    212
17841    186
13174    169
        ...
17870      1
16353      1
12755      1
17925      1
15769      1
Name: count, Length: 650, dtype: int64